### ISSUE TITLE
Vấn đề về wireshark

### ISSUE THREAD

**Issue by dragoncog2** [1412661/SimpleWebServer#19]
Do tao chạy máy ảo nên có khá nhiều card mạng, ko biết bắt cái nào và vấn đề là linux ko có bắt cái nào cả
![image](https://cloud.githubusercontent.com/assets/27731336/25305084/06610ebc-279f-11e7-90eb-a65612818977.png)

**Comment by baonq-me** [comment]
Bắt ở card lo.

**Comment by dragoncog2** [comment]
Đã thử bắt ở card Loopback nhưng vẫn vậy
![image](https://cloud.githubusercontent.com/assets/27731336/25305311/28265d28-27a3-11e7-8612-0508bb3835a7.png)

**Comment by baonq-me** [comment]
Chạy Wireshark dưới quyền sudo (mở command line lên gõ sudo wireshark)
